# Generated by Django 5.0.3 on 2024-03-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
            ],
        ),
    ]
